=== FloEdelmann/open-fixture-library/schemas/plugin.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",

  "definitions": {
    "htmlStringLines": {
      "description": "HTML string lines, will be joined by \\n.",
      "type": "array",
      "minItems": 1,
      "items": {
        "type": "string"
      }
    },
    "urlString": {
      "type": "string",
      "pattern": "^(ftp|http|https)://[^ \"]+$",
      "format": "uri"
    },
    "fileLocations": {
      "type": "object",
      "minProperties": 1,
      "properties": {
        "main": { "type": "string" },
        "user": { "type": "string" }
      },
      "additionalProperties": false
    }
  },

  "type": "object",
  "properties": {
    "$schema": { "const": "../../schemas/plugin.json" },
    "name": {
      "type": "string"
    },
    "previousVersions": {
      "type": "object",
      "minProperties": 1,
      "additionalProperties": {
        "type": "string"
      }
    },
    "description": { "$ref": "#/definitions/htmlStringLines" },
    "links": {
      "type": "object",
      "minProperties": 1,
      "properties": {
        "Website": { "$ref": "#/definitions/urlString" },
        "Fixture library download": { "$ref": "#/definitions/urlString" },
        "Fixture format documentation": { "$ref": "#/definitions/urlString" }
      },
      "additionalProperties": { "$ref": "#/definitions/urlString" }
    },
    "fixtureUsage": { "$ref": "#/definitions/htmlStringLines" },
    "fileLocations": {
      "type": "object",
      "minProperties": 1,
      "properties": {
        "subDirectoriesAllowed": {
          "type": "boolean"
        },
        "Windows": { "$ref": "#/definitions/fileLocations" },
        "Mac OS": { "$ref": "#/definitions/fileLocations" },
        "Linux": { "$ref": "#/definitions/fileLocations" }
      },
      "additionalProperties": { "$ref": "#/definitions/fileLocations" }
    },
    "additionalInfo": { "$ref": "#/definitions/htmlStringLines" },
    "helpWanted": { "type": "string" }
  },
  "required": ["$schema", "name", "description", "links"],
  "additionalProperties": false
}

=== FloEdelmann/open-fixture-library/plugins/aglight/plugin.json
{
    "$schema": "../../schemas/plugin.json",

    "name": "AGLight v1.0.0",
    "previousVersions": {},
    "description": [
        "<p><em>AGLight</em> is a lighting software with a completely configurable UI.",
        "You can add different widgets and build your own user interface with drag and drop.</p>"
    ],
    "links": {
        "Website": "https://github.com/hrueger/AGLight/"
    },
    "fixtureUsage": [
        "<p>You don't need to download the fixtures, just click on the library button in the bottom statusbar and click update.</p>"
    ]
}
